In [1]:
import pandas as pd
from io import StringIO #biblioteka służąca jako "plik pamięci". W tym przypadku służy do ilustracji problemu.
import csv
import os

In [2]:
dane = \
'''A,B,C,D,E,F,G,H,I,J
0,1.0,2.0,3.0,4.0,5.0,,7.0,,9.0,10.0
1,11.0,12.0,,,15.0,16.0,,18.0,19.0
2,,22.0,23.0,24.0,25.0,,,,29.0,30.0'''
df = pd.read_csv(StringIO(dane))
df

A     B     C     D     E     F    G     H     I     J
0   1.0   2.0   3.0   4.0   5.0   NaN  7.0   NaN   9.0  10.0
1  11.0  12.0   NaN   NaN  15.0  16.0  NaN  18.0  19.0   NaN
2   NaN  22.0  23.0  24.0  25.0   NaN  NaN   NaN  29.0  30.0

In [3]:
from sklearn.impute import SimpleImputer  
import numpy as np
imp = SimpleImputer(missing_values=np.nan, strategy='mean') 
imp = imp.fit(df.values)
imputed_data = imp.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.,  5., 16.,  7., 18.,  9., 10.],
       [11., 12., 13., 14., 15., 16.,  7., 18., 19., 20.],
       [ 6., 22., 23., 24., 25., 16.,  7., 18., 29., 30.]])

In [4]:
dane = \
'''A,B,C,D,E,F,G,H,I,J
0,1.0,2.0,3.0,4.0,5.0,,7.0,,9.0,10.0
1,11.0,12.0,,,15.0,16.0,,18.0,19.0
2,,22.0,23.0,24.0,25.0,,,,29.0,30.0'''
df = pd.read_csv(StringIO(dane))
df

A     B     C     D     E     F    G     H     I     J
0   1.0   2.0   3.0   4.0   5.0   NaN  7.0   NaN   9.0  10.0
1  11.0  12.0   NaN   NaN  15.0  16.0  NaN  18.0  19.0   NaN
2   NaN  22.0  23.0  24.0  25.0   NaN  NaN   NaN  29.0  30.0

In [5]:
df_t = df.T

In [6]:
df_t

0     1     2
A   1.0  11.0   NaN
B   2.0  12.0  22.0
C   3.0   NaN  23.0
D   4.0   NaN  24.0
E   5.0  15.0  25.0
F   NaN  16.0   NaN
G   7.0   NaN   NaN
H   NaN  18.0   NaN
I   9.0  19.0  29.0
J  10.0   NaN  30.0

In [7]:
df=df_t

In [8]:
from sklearn.impute import SimpleImputer  
import numpy as np
imp = SimpleImputer(missing_values=np.nan, strategy='mean') 
imp = imp.fit(df.values)
imputed_data = imp.transform(df.values)
imputed_data

array([[ 1.        , 11.        , 25.5       ],
       [ 2.        , 12.        , 22.        ],
       [ 3.        , 15.16666667, 23.        ],
       [ 4.        , 15.16666667, 24.        ],
       [ 5.        , 15.        , 25.        ],
       [ 5.125     , 16.        , 25.5       ],
       [ 7.        , 15.16666667, 25.5       ],
       [ 5.125     , 18.        , 25.5       ],
       [ 9.        , 19.        , 29.        ],
       [10.        , 15.16666667, 30.        ]])

In [9]:
import glob
import pandas as pd

df.to_csv('liczby2.csv')

In [10]:
dane = \
'''kolor,rozmiar,cena,etykiety klas
0,zielony,M,50.5,klasa1
1,czerwony,L,52.5,klasa2
2,niebieski,XL,57.5,klasa1
3,fioletowy,S,59.5,klasa1
4,czerwony,L,48.5,klasa3
5,zielony,XL,48.5,klasa2
6,brazowy,M,51.5,klasa1
7,fioletowy,L,53.5,klasa3
8,niebieski,S,61.5,klasa3
9,czerwony,XXL,65.5,klasa1'''
df = pd.read_csv(StringIO(dane))
df

kolor rozmiar  cena etykiety klas
0    zielony       M  50.5        klasa1
1   czerwony       L  52.5        klasa2
2  niebieski      XL  57.5        klasa1
3  fioletowy       S  59.5        klasa1
4   czerwony       L  48.5        klasa3
5    zielony      XL  48.5        klasa2
6    brazowy       M  51.5        klasa1
7  fioletowy       L  53.5        klasa3
8  niebieski       S  61.5        klasa3
9   czerwony     XXL  65.5        klasa1

In [11]:
 #Zidentyfikowanie brakujących danych w zbiorze danych
 df.isnull().sum()

kolor            0
rozmiar          0
cena             0
etykiety klas    0
dtype: int64

In [12]:
map = {           #konwersja wartości porządkowych na wartości liczbowe, aby algorytm nauczania mógł prawidłowo odczytać wartości porządkowe
    'XXL' : 5,
    'XL' : 4,
    'L' : 3,
    'M' : 2,
    'S' : 1,
}
df['rozmiar'] = df['rozmiar'].map(map) #użycie funkcji map() do konwersji słów na liczby
df

kolor  rozmiar  cena etykiety klas
0    zielony        2  50.5        klasa1
1   czerwony        3  52.5        klasa2
2  niebieski        4  57.5        klasa1
3  fioletowy        1  59.5        klasa1
4   czerwony        3  48.5        klasa3
5    zielony        4  48.5        klasa2
6    brazowy        2  51.5        klasa1
7  fioletowy        3  53.5        klasa3
8  niebieski        1  61.5        klasa3
9   czerwony        5  65.5        klasa1

In [13]:
rev_map = {v: k for k, v in map.items()}   #proces odwrotny, czyli przywrócenie wartości porządkowych z wartości liczbowych
df['rozmiar'].map(rev_map)

0      M
1      L
2     XL
3      S
4      L
5     XL
6      M
7      L
8      S
9    XXL
Name: rozmiar, dtype: object

In [14]:
map_klasa = {label:idx for idx,label in enumerate(np.unique(df['etykiety klas']))} #konwersja przy użyciu funkcji enumerate()
map_klasa

{'klasa1': 0, 'klasa2': 1, 'klasa3': 2}

In [15]:
df['etykiety klas'] = df['etykiety klas'].map(map_klasa) #zastosowanie mapowania do zaimplementowania wartości liczbowej do zbioru danych
df

kolor  rozmiar  cena  etykiety klas
0    zielony        2  50.5              0
1   czerwony        3  52.5              1
2  niebieski        4  57.5              0
3  fioletowy        1  59.5              0
4   czerwony        3  48.5              2
5    zielony        4  48.5              1
6    brazowy        2  51.5              0
7  fioletowy        3  53.5              2
8  niebieski        1  61.5              2
9   czerwony        5  65.5              0

In [16]:
#alternatywna wersja funkcji mapowania poprzez użycie biblioteki sklearn i LabelEncoder
from sklearn.preprocessing import LabelEncoder 
klasa_et = LabelEncoder()
y = klasa_et.fit_transform(df['etykiety klas'].values)    # klasa_et.inverse_transform(y)
y

array([0, 1, 0, 0, 2, 1, 0, 2, 2, 0])

In [17]:
X = df[['kolor', 'rozmiar', 'cena']].values 
kolor_et = LabelEncoder()
X[:, 0] = kolor_et.fit_transform(X[:, 0]) #transformowanie pierwszej kolumny (w tym przypadku koloru) z wartości nominalnych na wartości liczbowe
X

array([[4, 2, 50.5],
       [1, 3, 52.5],
       [3, 4, 57.5],
       [2, 1, 59.5],
       [1, 3, 48.5],
       [4, 4, 48.5],
       [0, 2, 51.5],
       [2, 3, 53.5],
       [3, 1, 61.5],
       [1, 5, 65.5]], dtype=object)

In [18]:
from sklearn.preprocessing import OneHotEncoder #kodowanie gorącojedynkowe
from sklearn.compose import ColumnTransformer  #transformacja kolumn

ohe = ColumnTransformer([("kolor", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ohe.fit_transform(X)
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [19]:
 pd.get_dummies(df[['cena', 'kolor', 'rozmiar']]) #funkcja manekina

cena  rozmiar  ...  kolor_niebieski  kolor_zielony
0  50.5        2  ...                0              1
1  52.5        3  ...                0              0
2  57.5        4  ...                1              0
3  59.5        1  ...                0              0
4  48.5        3  ...                0              0
5  48.5        4  ...                0              1
6  51.5        2  ...                0              0
7  53.5        3  ...                0              0
8  61.5        1  ...                1              0
9  65.5        5  ...                0              0

[10 rows x 7 columns]

In [20]:
import glob
import pandas as pd

df.to_csv('koszulki2.csv')